### Shorten a URL
POST http://localhost:8080/shorten
Accept: application/json
Content-Type: application/json

{
    "url": "https://localhost:8080/shorten-2"
}

### Get original URL
GET http://localhost:8080/-174453794